import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white shadow-md py-4">
          <div className="container mx-auto flex items-center justify-center">
            <a href={"/"}>
              <h1 className="text-4xl text-blue-800 font-bold">Find My Job</h1>
            </a>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
