import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-20 shadow-md content-center">
          <h1 className="text-4xl text-blue-800 font-bold text-center">Find my Job</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
